# override file for local dev environment
version: "3.9"
services:
  redis:
    ports:
      - "${REDIS_PORT_EXT:-6379}:${REDIS_PORT}"

  postgres:
    ports:
      - "${DB_EXTERNAL_PORT:-5432}:${DB_PORT}"

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    working_dir: /app
    volumes:
      - type: bind
        source: ./public
        target: /app/public
#    ports:
#      - "${WEB_PORT_EXT:-80}:80"
    labels:
      - traefik.http.routers.nginx-blogger-api.rule=Host(`blogger-api.loc`)
#      - traefik.http.routers.nginx-dashboard.tls=true
      - traefik.docker.network=traefik_external
    networks:
      - default
      - traefik_external

  init-job:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: dev
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./docker/php-fpm/php-ini-overrides.ini
        target: /usr/local/etc/php/conf.d/99-overrides.ini

  php-fpm:
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "phpstorm-docker-local-blogger-api"
      XDEBUG_CONFIG: "start_with_request=trigger client_host=host.docker.internal client_port=9000 discover_client_host=0"
      PHP_IDE_CONFIG: "serverName=blogger-api-local-docker"
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: dev
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./docker/php-fpm/php-ini-overrides.ini
        target: /usr/local/etc/php/conf.d/99-overrides.ini

networks:
  traefik_external:
    external: true
